Fixed shellcheck errors.

diff --git a/shflags b/shflags
--- a/shflags
+++ b/shflags
@@ -1,6 +1,6 @@
 # vim:et:ft=sh:sts=2:sw=2
 #
-# Copyright 2008-2020 Kate Ward. All Rights Reserved.
+# Copyright 2008-2023 Kate Ward. All Rights Reserved.
 # Released under the Apache License 2.0 license.
 # http://www.apache.org/licenses/LICENSE-2.0
 #
@@ -150,16 +150,16 @@ __FLAGS_LEVEL_DEFAULT=${FLAGS_LEVEL_WARN}
 __flags_level=${__FLAGS_LEVEL_DEFAULT} # Current logging level.
 
 _flags_debug() {
-  if [ ${__flags_level} -le ${FLAGS_LEVEL_DEBUG} ]; then echo "flags:DEBUG $*" >&2; fi
+  if [ "${__flags_level}" -le "${FLAGS_LEVEL_DEBUG}" ]; then echo "flags:DEBUG $*" >&2; fi
 }
 _flags_info() {
-  if [ ${__flags_level} -le ${FLAGS_LEVEL_INFO} ]; then echo "flags:INFO $*" >&2; fi
+  if [ "${__flags_level}" -le "${FLAGS_LEVEL_INFO}" ]; then echo "flags:INFO $*" >&2; fi
 }
 _flags_warn() {
-  if [ ${__flags_level} -le ${FLAGS_LEVEL_WARN} ]; then echo "flags:WARN $*" >&2; fi
+  if [ "${__flags_level}" -le "${FLAGS_LEVEL_WARN}" ]; then echo "flags:WARN $*" >&2; fi
 }
 _flags_error() {
-  if [ ${__flags_level} -le ${FLAGS_LEVEL_ERROR} ]; then echo "flags:ERROR $*" >&2; fi
+  if [ "${__flags_level}" -le "${FLAGS_LEVEL_ERROR}" ]; then echo "flags:ERROR $*" >&2; fi
 }
 _flags_fatal() {
   echo "flags:FATAL $*" >&2
@@ -167,7 +167,7 @@ _flags_fatal() {
 }
 
 # Get the logging level.
-flags_loggingLevel() { echo ${__flags_level}; }
+flags_loggingLevel() { echo "${__flags_level}"; }
 
 # Set the logging level by overriding the `__flags_level` variable.
 #
@@ -274,7 +274,7 @@ for __flags_const in ${__flags_constants}; do
     [123].*) readonly "${__flags_const}" ;;
     *)
       # Declare readonly constants globally.
-      # shellcheck disable=SC2039
+      # shellcheck disable=SC2039,SC3045
       readonly -g "${__flags_const}" ;;
   esac
 done
@@ -370,7 +370,7 @@ _flags_define() {
   # '!' is not done because it does not work on all shells.
   if [ ${_flags_return_} -eq ${FLAGS_TRUE} ]; then
     case ${_flags_type_} in
-      ${__FLAGS_TYPE_BOOLEAN})
+      "${__FLAGS_TYPE_BOOLEAN}")
         if _flags_validBool "${_flags_default_}"; then
           case ${_flags_default_} in
             true|t|0) _flags_default_=${FLAGS_TRUE} ;;
@@ -382,7 +382,7 @@ _flags_define() {
         fi
         ;;
 
-      ${__FLAGS_TYPE_FLOAT})
+      "${__FLAGS_TYPE_FLOAT}")
         if _flags_validFloat "${_flags_default_}"; then
           :
         else
@@ -391,7 +391,7 @@ _flags_define() {
         fi
         ;;
 
-      ${__FLAGS_TYPE_INTEGER})
+      "${__FLAGS_TYPE_INTEGER}")
         if _flags_validInt "${_flags_default_}"; then
           :
         else
@@ -400,7 +400,7 @@ _flags_define() {
         fi
         ;;
 
-      ${__FLAGS_TYPE_STRING}) ;;  # Everything in shell is a valid string.
+      "${__FLAGS_TYPE_STRING}") ;;  # Everything in shell is a valid string.
 
       *)
         flags_error="unrecognized flag type '${_flags_type_}'"
@@ -470,7 +470,7 @@ _flags_genOptStr() {
       _flags_fatal 'call to _flags_type_ failed'
     fi
     case ${_flags_optStrType_} in
-      ${__FLAGS_OPTSTR_SHORT})
+      "${__FLAGS_OPTSTR_SHORT}")
         _flags_shortName_="`_flags_getFlagInfo \
             "${_flags_usName_}" "${__FLAGS_INFO_SHORT}"`"
         if [ "${_flags_shortName_}" != "${__FLAGS_NULL}" ]; then
@@ -481,7 +481,7 @@ _flags_genOptStr() {
         fi
         ;;
 
-      ${__FLAGS_OPTSTR_LONG})
+      "${__FLAGS_OPTSTR_LONG}")
         _flags_opts_="${_flags_opts_:+${_flags_opts_},}${_flags_name_}"
         # getopt needs a trailing ':' to indicate a required argument
         [ "${_flags_type_}" -ne "${__FLAGS_TYPE_BOOLEAN}" ] && \
@@ -519,7 +519,7 @@ _flags_getFlagInfo() {
   eval "${_flags_strToEval_}"
   if [ -n "${_flags_infoValue_}" ]; then
     # Special value '§' indicates no help string provided.
-    [ "${_flags_gFI_info_}" = ${__FLAGS_INFO_HELP} \
+    [ "${_flags_gFI_info_}" = "${__FLAGS_INFO_HELP}" \
         -a "${_flags_infoValue_}" = '§' ] && _flags_infoValue_=''
     flags_return=${FLAGS_TRUE}
   else
@@ -684,7 +684,7 @@ _flags_validInt() {
 #   integer: a FLAGS success condition
 _flags_getoptStandard() {
   flags_return=${FLAGS_TRUE}
-  _flags_shortOpts_=`_flags_genOptStr ${__FLAGS_OPTSTR_SHORT}`
+  _flags_shortOpts_=`_flags_genOptStr "${__FLAGS_OPTSTR_SHORT}"`
 
   # Check for spaces in passed options.
   for _flags_opt_ in "$@"; do
@@ -722,10 +722,10 @@ _flags_getoptStandard() {
 #   integer: a FLAGS success condition
 _flags_getoptEnhanced() {
   flags_return=${FLAGS_TRUE}
-  _flags_shortOpts_=`_flags_genOptStr ${__FLAGS_OPTSTR_SHORT}`
+  _flags_shortOpts_=`_flags_genOptStr "${__FLAGS_OPTSTR_SHORT}"`
   _flags_boolOpts_=`echo "${__flags_boolNames}" \
       |sed 's/^ *//;s/ *$//;s/ /,/g'`
-  _flags_longOpts_=`_flags_genOptStr ${__FLAGS_OPTSTR_LONG}`
+  _flags_longOpts_=`_flags_genOptStr "${__FLAGS_OPTSTR_LONG}"`
 
   __flags_opts=`${FLAGS_GETOPT_CMD} \
       -o "${_flags_shortOpts_}" \
@@ -761,6 +761,7 @@ _flags_parseGetopt() {
     set -- $@
   else
     # Note the quotes around the `$@` -- they are essential!
+    #  shellcheck disable=SC2294
     eval set -- "$@"
   fi
 
@@ -826,12 +827,11 @@ _flags_parseGetopt() {
 
     # Set new flag value.
     _flags_usName_=`_flags_underscoreName "${_flags_name_}"`
-    [ ${_flags_type_} -eq ${__FLAGS_TYPE_NONE} ] && \
-        _flags_type_=`_flags_getFlagInfo \
-            "${_flags_usName_}" ${__FLAGS_INFO_TYPE}`
+    [ "${_flags_type_}" -eq "${__FLAGS_TYPE_NONE}" ] && \
+        _flags_type_=`_flags_getFlagInfo "${_flags_usName_}" "${__FLAGS_INFO_TYPE}"`
     case ${_flags_type_} in
-      ${__FLAGS_TYPE_BOOLEAN})
-        if [ ${_flags_len_} -eq ${__FLAGS_LEN_LONG} ]; then
+      "${__FLAGS_TYPE_BOOLEAN}")
+        if [ "${_flags_len_}" -eq "${__FLAGS_LEN_LONG}" ]; then
           if [ "${_flags_arg_}" != "${__FLAGS_NULL}" ]; then
             eval "FLAGS_${_flags_usName_}=${FLAGS_TRUE}"
           else
@@ -850,7 +850,7 @@ _flags_parseGetopt() {
         fi
         ;;
 
-      ${__FLAGS_TYPE_FLOAT})
+      "${__FLAGS_TYPE_FLOAT}")
         if _flags_validFloat "${_flags_arg_}"; then
           eval "FLAGS_${_flags_usName_}='${_flags_arg_}'"
         else
@@ -860,7 +860,7 @@ _flags_parseGetopt() {
         fi
         ;;
 
-      ${__FLAGS_TYPE_INTEGER})
+      "${__FLAGS_TYPE_INTEGER}")
         if _flags_validInt "${_flags_arg_}"; then
           eval "FLAGS_${_flags_usName_}='${_flags_arg_}'"
         else
@@ -870,7 +870,7 @@ _flags_parseGetopt() {
         fi
         ;;
 
-      ${__FLAGS_TYPE_STRING})
+      "${__FLAGS_TYPE_STRING}")
         eval "FLAGS_${_flags_usName_}='${_flags_arg_}'"
         ;;
     esac
@@ -888,7 +888,7 @@ _flags_parseGetopt() {
 
     # Shift the option and non-boolean arguments out.
     shift
-    [ "${_flags_type_}" != ${__FLAGS_TYPE_BOOLEAN} ] && shift
+    [ "${_flags_type_}" != "${__FLAGS_TYPE_BOOLEAN}" ] && shift
   done
 
   # Give user back non-flag arguments.
@@ -923,6 +923,7 @@ _flags_math() {
     flags_return=$?
     unset _flags_expr_
   else
+    #  shellcheck disable=SC2294
     eval expr "$@"
     flags_return=$?
   fi
@@ -961,7 +962,7 @@ _flags_strlen() {
 #   None
 # Returns:
 #   bool: true if built-ins should be used
-_flags_useBuiltin() { return ${__FLAGS_USE_BUILTIN}; }
+_flags_useBuiltin() { return "${__FLAGS_USE_BUILTIN}"; }
 
 #------------------------------------------------------------------------------
 # public functions
@@ -979,12 +980,12 @@ _flags_useBuiltin() { return ${__FLAGS_USE_BUILTIN}; }
 # and whose short name was 'x', and the default value was 'false'. This flag
 # could be explicitly set to 'true' with '--update' or by '-x', and it could be
 # explicitly set to 'false' with '--noupdate'.
-DEFINE_boolean() { _flags_define ${__FLAGS_TYPE_BOOLEAN} "$@"; }
+DEFINE_boolean() { _flags_define "${__FLAGS_TYPE_BOOLEAN}" "$@"; }
 
 # Other basic flags.
-DEFINE_float()   { _flags_define ${__FLAGS_TYPE_FLOAT} "$@"; }
-DEFINE_integer() { _flags_define ${__FLAGS_TYPE_INTEGER} "$@"; }
-DEFINE_string()  { _flags_define ${__FLAGS_TYPE_STRING} "$@"; }
+DEFINE_float()   { _flags_define "${__FLAGS_TYPE_FLOAT}" "$@"; }
+DEFINE_integer() { _flags_define "${__FLAGS_TYPE_INTEGER}" "$@"; }
+DEFINE_string()  { _flags_define "${__FLAGS_TYPE_STRING}" "$@"; }
 
 # Parse the flags.
 #
@@ -1101,13 +1102,13 @@ flags_help() {
       flags_usName_=`_flags_underscoreName "${flags_name_}"`
 
       flags_default_=`_flags_getFlagInfo \
-          "${flags_usName_}" ${__FLAGS_INFO_DEFAULT}`
+          "${flags_usName_}" "${__FLAGS_INFO_DEFAULT}"`
       flags_help_=`_flags_getFlagInfo \
-          "${flags_usName_}" ${__FLAGS_INFO_HELP}`
+          "${flags_usName_}" "${__FLAGS_INFO_HELP}"`
       flags_short_=`_flags_getFlagInfo \
-          "${flags_usName_}" ${__FLAGS_INFO_SHORT}`
+          "${flags_usName_}" "${__FLAGS_INFO_SHORT}"`
       flags_type_=`_flags_getFlagInfo \
-          "${flags_usName_}" ${__FLAGS_INFO_TYPE}`
+          "${flags_usName_}" "${__FLAGS_INFO_TYPE}"`
 
       [ "${flags_short_}" != "${__FLAGS_NULL}" ] && \
           flags_flagStr_="-${flags_short_}"
@@ -1116,23 +1117,23 @@ flags_help() {
         [ "${flags_short_}" != "${__FLAGS_NULL}" ] && \
             flags_flagStr_="${flags_flagStr_},"
         # Add [no] to long boolean flag names, except the 'help' flag.
-        [ "${flags_type_}" -eq ${__FLAGS_TYPE_BOOLEAN} \
+        [ "${flags_type_}" -eq "${__FLAGS_TYPE_BOOLEAN}" \
           -a "${flags_usName_}" != 'help' ] && \
             flags_boolStr_='[no]'
         flags_flagStr_="${flags_flagStr_}--${flags_boolStr_}${flags_name_}:"
       fi
 
       case ${flags_type_} in
-        ${__FLAGS_TYPE_BOOLEAN})
+        "${__FLAGS_TYPE_BOOLEAN}")
           if [ "${flags_default_}" -eq ${FLAGS_TRUE} ]; then
             flags_defaultStr_='true'
           else
             flags_defaultStr_='false'
           fi
           ;;
-        ${__FLAGS_TYPE_FLOAT}|${__FLAGS_TYPE_INTEGER})
+        "${__FLAGS_TYPE_FLOAT}"|"${__FLAGS_TYPE_INTEGER}")
           flags_defaultStr_=${flags_default_} ;;
-        ${__FLAGS_TYPE_STRING}) flags_defaultStr_="'${flags_default_}'" ;;
+        "${__FLAGS_TYPE_STRING}") flags_defaultStr_="'${flags_default_}'" ;;
       esac
       flags_defaultStr_="(default: ${flags_defaultStr_})"
 
@@ -1201,7 +1202,7 @@ flags_reset() {
   __flags_definedNames=' '
 
   # Reset logging level back to default.
-  flags_setLoggingLevel ${__FLAGS_LEVEL_DEFAULT}
+  flags_setLoggingLevel "${__FLAGS_LEVEL_DEFAULT}"
 
   unset flags_name_ flags_type_ flags_strToEval_ flags_usName_
 }
