Ran shflags_test_helpers through ShellCheck.

diff --git a/shflags_test_helpers b/shflags_test_helpers
--- a/shflags_test_helpers
+++ b/shflags_test_helpers
@@ -1,65 +1,77 @@
 # vim:et:ft=sh:sts=2:sw=2
 #
 # shFlags unit test common functions
+#
+# Copyright 2008-2017 Kate Ward. All Rights Reserved.
+# Released under the Apache 2.0 license.
+#
+# Author: kate.ward@forestent.com (Kate Ward)
+# https://github.com/kward/shflags
+#
+### ShellCheck (http://www.shellcheck.net/)
+# Disable source following.
+#   shellcheck disable=SC1090,SC1091
+# $() are not fully portable (POSIX != portable).
+#   shellcheck disable=SC2006
+# Disagree with [ p ] && [ q ] vs [ p -a -q ] recommendation.
+#   shellcheck disable=SC2166
 
-__th_skipping=0
-
-# treat unset variables as an error
+# Treat unset variables as an error.
 set -u
 
-# set shwordsplit for zsh
+# Set shwordsplit for zsh.
 [ -n "${ZSH_VERSION:-}" ] && setopt shwordsplit
 
-# my name
-TH_MY_NAME=`basename "$0"`
+# Message functions.
+th_trace() { echo "test:TRACE $*" >&2; }
+th_debug() { echo "test:DEBUG $*" >&2; }
+th_info() { echo "test:INFO $*" >&2; }
+th_warn() { echo "test:WARN $*" >&2; }
+th_error() { echo "test:ERROR $*" >&2; }
+th_fatal() { echo "test:FATAL $*" >&2; exit 1; }
 
-# path to shFlags library. can be overridden by setting SHFLAGS_INC
-TH_SHFLAGS=${SHFLAGS_INC:-./shflags}
+# My name.
+TH_MY_NAME=`basename "$0"` || th_fatal 'Error executing basename.'
+export TH_MY_NAME
+
+# Path to shFlags library. Can be overridden by setting SHFLAGS_INC.
+export TH_SHFLAGS=${SHFLAGS_INC:-./shflags}
 
 # Path to shUnit2 library. Can be overridden by setting SHUNIT_INC.
 export TH_SHUNIT=${SHUNIT_INC:-lib/shunit2}
 
-TH_BOOL_VALID='true t 0 false f 1'
-TH_BOOL_INVALID='123 123.0 invalid'
-TH_FLOAT_VALID='-1234.0 -1.0 -.123 0.0 0. .123 1.0 1234.0'
-TH_FLOAT_INVALID='true false 1.2.3 -1.2.3 ""'
-TH_INT_VALID='-1234 -1 0 1 1234'
-TH_INT_INVALID='true false -1.0 -.123 0.0 .123 1.0 ""'
+export TH_BOOL_VALID='true t 0 false f 1'
+export TH_BOOL_INVALID='123 123.0 invalid'
+export TH_FLOAT_VALID='-1234.0 -1.0 -.123 0.0 0. .123 1.0 1234.0'
+export TH_FLOAT_INVALID='true false 1.2.3 -1.2.3 ""'
+export TH_INT_VALID='-1234 -1 0 1 1234'
+export TH_INT_INVALID='true false -1.0 -.123 0.0 .123 1.0 ""'
 
 #
-# test helper functions
+# Test helper functions.
 #
 
-# message functions
-th_trace() { echo "test:TRACE $@" >&2; }
-th_debug() { echo "test:DEBUG $@" >&2; }
-th_info() { echo "test:INFO $@" >&2; }
-th_warn() { echo "test:WARN $@" >&2; }
-th_error() { echo "test:ERROR $@" >&2; }
-th_fatal() { echo "test:FATAL $@" >&2; }
-
-th_oneTimeSetUp()
-{
-  # load shFlags
+th_oneTimeSetUp() {
+  # Load shFlags.
+  # shellcheck disable=SC2034
   [ -n "${ZSH_VERSION:-}" ] && FLAGS_PARENT=$0
-  . ${TH_SHFLAGS}
+  . "${TH_SHFLAGS}"
 
-  # these files will be cleaned up automatically by shUnit2
-  tmpDir=${SHUNIT_TMPDIR}
-  stdoutF="${tmpDir}/stdout"
-  stderrF="${tmpDir}/stderr"
-  returnF="${tmpDir}/return"
-  expectedF="${tmpDir}/expected"
+  # These files will be cleaned up automatically by shUnit2.
+  export tmpDir=${SHUNIT_TMPDIR}
+  stdoutF="${tmpDir}/stdout" && touch "${stdoutF}"
+  stderrF="${tmpDir}/stderr" && touch "${stderrF}"
+  returnF="${tmpDir}/return" && touch "${returnF}"
+  expectedF="${tmpDir}/expected" && touch "${expectedF}"
 }
 
-th_showOutput()
-{
+th_showOutput() {
   _th_rtrn=$1
   _th_stdout=$2
   _th_stderr=$3
 
   isSkipping
-  if [ $? -eq ${SHUNIT_FALSE} -a ${_th_rtrn} != ${FLAGS_TRUE} ]; then
+  if [ $? -eq "${SHUNIT_FALSE}" -a "${_th_rtrn}" != "${FLAGS_TRUE}" ]; then
     if [ -n "${_th_stdout}" -a -s "${_th_stdout}" ]; then
       echo '>>> STDOUT' >&2
       cat "${_th_stdout}" >&2
@@ -85,12 +97,11 @@ th_queryReturn() {
     cat "${returnF}"
     return $?
   fi
-  echo ${SHUNIT_ERROR}
-  return ${SHUNIT_ERROR}
+  echo "${SHUNIT_ERROR}"
+  return "${SHUNIT_ERROR}"
 }
 
-_th_assertMsg()
-{
+_th_assertMsg() {
   _th_alert_type_=$1
   _th_alert_msg_=$2
   _th_msg_=$3
