Update the shFlags library to most recent version.

diff --git a/lib/shflags b/lib/shflags
--- a/lib/shflags
+++ b/lib/shflags
@@ -1,33 +1,33 @@
-# $Id: shflags 189 2013-01-15 00:13:10Z kate.ward@forestent.com $
 # vim:et:ft=sh:sts=2:sw=2
 #
-# Copyright 2008 Kate Ward. All Rights Reserved.
-# Released under the LGPL (GNU Lesser General Public License)
+# Copyright 2008-2017 Kate Ward. All Rights Reserved.
+# Released under the Apache License 2.0 license.
+# http://www.apache.org/licenses/LICENSE-2.0
 #
 # shFlags -- Advanced command-line flag library for Unix shell scripts.
-# http://code.google.com/p/shflags/
+# https://github.com/kward/shflags
 #
 # Author: kate.ward@forestent.com (Kate Ward)
 #
-# This module implements something like the google-gflags library available
-# from http://code.google.com/p/google-gflags/.
+# This module implements something like the gflags library available
+# from https://github.com/gflags/gflags.
 #
 # FLAG TYPES: This is a list of the DEFINE_*'s that you can do.  All flags take
 # a name, default value, help-string, and optional 'short' name (one-letter
-# name).  Some flags have other arguments, which are described with the flag.
+# name). Some flags have other arguments, which are described with the flag.
 #
-# DEFINE_string: takes any input, and intreprets it as a string.
+# DEFINE_string: takes any input, and interprets it as a string.
 #
 # DEFINE_boolean: does not take any arguments. Say --myflag to set
 #   FLAGS_myflag to true, or --nomyflag to set FLAGS_myflag to false. For short
 #   flags, passing the flag on the command-line negates the default value, i.e.
 #   if the default is true, passing the flag sets the value to false.
 #
-# DEFINE_float: takes an input and intreprets it as a floating point number. As
+# DEFINE_float: takes an input and interprets it as a floating point number. As
 #   shell does not support floats per-se, the input is merely validated as
 #   being a valid floating point value.
 #
-# DEFINE_integer: takes an input and intreprets it as an integer.
+# DEFINE_integer: takes an input and interprets it as an integer.
 #
 # SPECIAL FLAGS: There are a few flags that have special meaning:
 #   --help (or -?)  prints a list of all the flags in a human-readable fashion
@@ -82,27 +82,42 @@
 # Notes:
 # - lists of strings are space separated, and a null value is the '~' char.
 
-# return if FLAGS already loaded
+# Return if FLAGS already loaded.
 [ -n "${FLAGS_VERSION:-}" ] && return 0
-FLAGS_VERSION='1.0.4pre'
+FLAGS_VERSION='1.2.1'
 
-# return values that scripts can use
+# Return values that scripts can use.
 FLAGS_TRUE=0
 FLAGS_FALSE=1
 FLAGS_ERROR=2
 
-# determine some reasonable command defaults
-__FLAGS_UNAME_S=`uname -s`
-case "${__FLAGS_UNAME_S}" in
-  BSD) __FLAGS_EXPR_CMD='gexpr' ;;
-  *) __FLAGS_EXPR_CMD='expr' ;;
-esac
+# Logging levels.
+FLAGS_LEVEL_DEBUG=0
+FLAGS_LEVEL_INFO=1
+FLAGS_LEVEL_WARN=2
+FLAGS_LEVEL_ERROR=3
+FLAGS_LEVEL_FATAL=4
+__FLAGS_LEVEL_DEFAULT=${FLAGS_LEVEL_WARN}
 
-# commands a user can override if needed
+# Determine some reasonable command defaults.
+__FLAGS_EXPR_CMD='expr --'
+__FLAGS_UNAME_S=`uname -s`
+if [ "${__FLAGS_UNAME_S}" = 'BSD' ]; then
+  __FLAGS_EXPR_CMD='gexpr --'
+else
+  _flags_output_=`${__FLAGS_EXPR_CMD} 2>&1`
+  if [ $? -eq ${FLAGS_TRUE} -a "${_flags_output_}" = '--' ]; then
+    # We are likely running inside BusyBox.
+    __FLAGS_EXPR_CMD='expr'
+  fi
+  unset _flags_output_
+fi
+
+# Commands a user can override if needed.
 FLAGS_EXPR_CMD=${FLAGS_EXPR_CMD:-${__FLAGS_EXPR_CMD}}
 FLAGS_GETOPT_CMD=${FLAGS_GETOPT_CMD:-getopt}
 
-# specific shell checks
+# Specific shell checks.
 if [ -n "${ZSH_VERSION:-}" ]; then
   setopt |grep "^shwordsplit$" >/dev/null
   if [ $? -ne ${FLAGS_TRUE} ]; then
@@ -114,7 +129,7 @@ if [ -n "${ZSH_VERSION:-}" ]; then
   fi
 fi
 
-# can we use built-ins?
+# Can we use built-ins?
 ( echo "${FLAGS_TRUE#0}"; ) >/dev/null 2>&1
 if [ $? -eq ${FLAGS_TRUE} ]; then
   __FLAGS_USE_BUILTIN=${FLAGS_TRUE}
@@ -122,15 +137,16 @@ else
   __FLAGS_USE_BUILTIN=${FLAGS_FALSE}
 fi
 
+
 #
-# constants
+# Constants.
 #
 
-# reserved flag names
+# Reserved flag names.
 __FLAGS_RESERVED_LIST=' ARGC ARGV ERROR FALSE GETOPT_CMD HELP PARENT TRUE '
 __FLAGS_RESERVED_LIST="${__FLAGS_RESERVED_LIST} VERSION "
 
-# getopt version
+# getopt version.
 __FLAGS_GETOPT_VERS_STD=0
 __FLAGS_GETOPT_VERS_ENH=1
 __FLAGS_GETOPT_VERS_BSD=2
@@ -138,6 +154,7 @@ __FLAGS_GETOPT_VERS_BSD=2
 ${FLAGS_GETOPT_CMD} >/dev/null 2>&1
 case $? in
   0) __FLAGS_GETOPT_VERS=${__FLAGS_GETOPT_VERS_STD} ;;  # bsd getopt
+  1) __FLAGS_GETOPT_VERS=${__FLAGS_GETOPT_VERS_ENH} ;;  # BusyBox getopt.
   2)
     # TODO(kward): look into '-T' option to test the internal getopt() version
     if [ "`${FLAGS_GETOPT_CMD} --version`" = '-- ' ]; then
@@ -155,65 +172,102 @@ __FLAGS_OPTSTR_LONG=1
 
 __FLAGS_NULL='~'
 
-# flag info strings
+# Flag info strings.
 __FLAGS_INFO_DEFAULT='default'
 __FLAGS_INFO_HELP='help'
 __FLAGS_INFO_SHORT='short'
 __FLAGS_INFO_TYPE='type'
 
-# flag lengths
+# Flag lengths.
 __FLAGS_LEN_SHORT=0
 __FLAGS_LEN_LONG=1
 
-# flag types
+# Flag types.
 __FLAGS_TYPE_NONE=0
 __FLAGS_TYPE_BOOLEAN=1
 __FLAGS_TYPE_FLOAT=2
 __FLAGS_TYPE_INTEGER=3
 __FLAGS_TYPE_STRING=4
 
-# set the constants readonly
+# Set the constants readonly.
 __flags_constants=`set |awk -F= '/^FLAGS_/ || /^__FLAGS_/ {print $1}'`
 for __flags_const in ${__flags_constants}; do
-  # skip certain flags
+  # Skip certain flags.
   case ${__flags_const} in
     FLAGS_HELP) continue ;;
     FLAGS_PARENT) continue ;;
   esac
-  # set flag readonly
+  # Set flag readonly.
   if [ -z "${ZSH_VERSION:-}" ]; then
     readonly ${__flags_const}
-  else  # handle zsh
-    case ${ZSH_VERSION} in
-      [123].*) readonly ${__flags_const} ;;
-      *) readonly -g ${__flags_const} ;;  # declare readonly constants globally
-    esac
+    continue
   fi
+  case ${ZSH_VERSION} in
+    [123].*) readonly ${__flags_const} ;;
+    *) readonly -g ${__flags_const} ;;  # Declare readonly constants globally.
+  esac
 done
 unset __flags_const __flags_constants
 
 #
-# internal variables
+# Internal variables.
 #
 
-# space separated lists
-__flags_boolNames=' '  # boolean flag names
-__flags_longNames=' '  # long flag names
-__flags_shortNames=' '  # short flag names
-__flags_definedNames=' ' # defined flag names (used for validation)
+# Space separated lists.
+__flags_boolNames=' '     # Boolean flag names.
+__flags_longNames=' '     # Long flag names.
+__flags_shortNames=' '    # Short flag names.
+__flags_definedNames=' '  # Defined flag names (used for validation).
 
-__flags_columns=''  # screen width in columns
-__flags_opts=''  # temporary storage for parsed getopt flags
+__flags_columns=''  # Screen width in columns.
+__flags_level=0     # Default logging level.
+__flags_opts=''     # Temporary storage for parsed getopt flags.
 
 #------------------------------------------------------------------------------
-# private functions
+# Private functions.
 #
 
-# logging functions
-_flags_debug() { echo "flags:DEBUG $@" >&2; }
-_flags_warn() { echo "flags:WARN $@" >&2; }
-_flags_error() { echo "flags:ERROR $@" >&2; }
-_flags_fatal() { echo "flags:FATAL $@" >&2; exit ${FLAGS_ERROR}; }
+# Logging functions.
+_flags_debug() {
+  [ ${__flags_level} -le ${FLAGS_LEVEL_DEBUG} ] || return
+  echo "flags:DEBUG $@" >&2
+}
+_flags_info() {
+  [ ${__flags_level} -le ${FLAGS_LEVEL_INFO} ] || return
+  echo "flags:INFO $@" >&2
+}
+_flags_warn() {
+  [ ${__flags_level} -le ${FLAGS_LEVEL_WARN} ] || return
+  echo "flags:WARN $@" >&2
+}
+_flags_error() {
+  [ ${__flags_level} -le ${FLAGS_LEVEL_ERROR} ] || return
+  echo "flags:ERROR $@" >&2
+}
+_flags_fatal() {
+  [ ${__flags_level} -le ${FLAGS_LEVEL_FATAL} ] || return
+  echo "flags:FATAL $@" >&2
+  exit ${FLAGS_ERROR}
+}
+
+# Get the logging level.
+flags_loggingLevel() { echo ${__flags_level}; }
+
+# Set the logging level.
+#
+# Args:
+#   _flags_level_: integer: new logging level
+# Returns:
+#   nothing
+flags_setLoggingLevel() {
+  [ $# -ne 1 ] && _flags_fatal "flags_setLevel(): logging level missing"
+  _flags_level_=$1
+  [ ${_flags_level_} -ge ${FLAGS_LEVEL_DEBUG} \
+    -a ${_flags_level_} -le ${FLAGS_LEVEL_FATAL} ] \
+      || _flags_fatal "Invalid logging level '${_flags_level_}' specified."
+  __flags_level=$1
+  unset _flags_level_
+}
 
 # Define a flag.
 #
@@ -226,11 +280,11 @@ _flags_fatal() { echo "flags:FATAL $@" >&2; exit ${FLAGS_ERROR}; }
 #   __flags_flagname_type - the type of flag (one of __FLAGS_TYPE_*)
 #
 # Args:
-#   _flags__type: integer: internal type of flag (__FLAGS_TYPE_*)
-#   _flags__name: string: long flag name
-#   _flags__default: default flag value
-#   _flags__help: string: help string
-#   _flags__short: string: (optional) short flag name
+#   _flags_type_: integer: internal type of flag (__FLAGS_TYPE_*)
+#   _flags_name_: string: long flag name
+#   _flags_default_: default flag value
+#   _flags_help_: string: help string
+#   _flags_short_: string: (optional) short flag name
 # Returns:
 #   integer: success of operation, or error
 _flags_define()
@@ -247,6 +301,10 @@ _flags_define()
   _flags_default_=$3
   _flags_help_=$4
   _flags_short_=${5:-${__FLAGS_NULL}}
+
+  _flags_debug "type:${_flags_type_} name:${_flags_name_}" \
+      "default:'${_flags_default_}' help:'${_flags_help_}'" \
+      "short:${_flags_short_}"
 
   _flags_return_=${FLAGS_TRUE}
   _flags_usName_=`_flags_underscoreName ${_flags_name_}`
@@ -332,7 +390,7 @@ _flags_define()
   fi
 
   if [ ${_flags_return_} -eq ${FLAGS_TRUE} ]; then
-    # store flag information
+    # Store flag information.
     eval "FLAGS_${_flags_usName_}='${_flags_default_}'"
     eval "__flags_${_flags_usName_}_${__FLAGS_INFO_TYPE}=${_flags_type_}"
     eval "__flags_${_flags_usName_}_${__FLAGS_INFO_DEFAULT}=\
@@ -437,7 +495,7 @@ _flags_getFlagInfo()
   _flags_infoVar_="__flags_${_flags_gFI_usName_}_${_flags_gFI_info_}"
   _flags_strToEval_="_flags_infoValue_=\"\${${_flags_infoVar_}:-}\""
   eval "${_flags_strToEval_}"
-  if [ -n "${_flags_infoValue_}" ]; then
+  if [ -n "${_flags_infoValue_+x}" ]; then
     flags_return=${FLAGS_TRUE}
   else
     # see if the _flags_gFI_usName_ variable is a string as strings can be
@@ -466,7 +524,7 @@ _flags_getFlagInfo()
   return ${flags_return}
 }
 
-# Check for presense of item in a list.
+# Check for presence of item in a list.
 #
 # Passed a string (e.g. 'abc'), this function will determine if the string is
 # present in the list of strings (e.g.  ' foo bar abc ').
@@ -480,12 +538,10 @@ _flags_itemInList() {
   _flags_str_=$1
   shift
 
-  echo " ${*:-} " |grep " ${_flags_str_} " >/dev/null
-  if [ $? -eq 0 ]; then
-    flags_return=${FLAGS_TRUE}
-  else
-    flags_return=${FLAGS_FALSE}
-  fi
+  case " ${*:-} " in
+    *\ ${_flags_str_}\ *) flags_return=${FLAGS_TRUE} ;;
+    *) flags_return=${FLAGS_FALSE} ;;
+  esac
 
   unset _flags_str_
   return ${flags_return}
@@ -540,8 +596,7 @@ _flags_validBool()
 #   _flags_float_: float: value to validate
 # Returns:
 #   bool: true if the value is a valid integer
-_flags_validFloat()
-{
+_flags_validFloat() {
   flags_return=${FLAGS_FALSE}
   [ -n "$1" ] || return ${flags_return}
   _flags_float_=$1
@@ -560,11 +615,11 @@ _flags_validFloat()
     flags_return=${FLAGS_TRUE}
     case ${_flags_float_} in
       -*)  # negative floats
-        _flags_test_=`${FLAGS_EXPR_CMD} -- "${_flags_float_}" :\
+        _flags_test_=`${FLAGS_EXPR_CMD} "${_flags_float_}" :\
             '\(-[0-9]*\.[0-9]*\)'`
         ;;
       *)  # positive floats
-        _flags_test_=`${FLAGS_EXPR_CMD} -- "${_flags_float_}" :\
+        _flags_test_=`${FLAGS_EXPR_CMD} "${_flags_float_}" :\
             '\([0-9]*\.[0-9]*\)'`
         ;;
     esac
@@ -594,7 +649,7 @@ _flags_validInt()
       if _flags_useBuiltin; then
         _flags_int_=${_flags_int_#-}
       else
-        _flags_int_=`${FLAGS_EXPR_CMD} -- "${_flags_int_}" : '-\([0-9][0-9]*\)'`
+        _flags_int_=`${FLAGS_EXPR_CMD} "${_flags_int_}" : '-\([0-9][0-9]*\)'`
       fi
       ;;
   esac
@@ -726,7 +781,7 @@ _flags_parseGetopt()
         if _flags_useBuiltin; then
           _flags_opt_=${_flags_opt_#*--}
         else
-          _flags_opt_=`${FLAGS_EXPR_CMD} -- "${_flags_opt_}" : '--\(.*\)'`
+          _flags_opt_=`${FLAGS_EXPR_CMD} "${_flags_opt_}" : '--\(.*\)'`
         fi
         _flags_len_=${__FLAGS_LEN_LONG}
         if _flags_itemInList "${_flags_opt_}" ${__flags_longNames}; then
@@ -737,7 +792,7 @@ _flags_parseGetopt()
             if _flags_useBuiltin; then
               _flags_name_=${_flags_opt_#*no}
             else
-              _flags_name_=`${FLAGS_EXPR_CMD} -- "${_flags_opt_}" : 'no\(.*\)'`
+              _flags_name_=`${FLAGS_EXPR_CMD} "${_flags_opt_}" : 'no\(.*\)'`
             fi
             _flags_type_=${__FLAGS_TYPE_BOOLEAN}
             _flags_arg_=${__FLAGS_NULL}
@@ -749,7 +804,7 @@ _flags_parseGetopt()
         if _flags_useBuiltin; then
           _flags_opt_=${_flags_opt_#*-}
         else
-          _flags_opt_=`${FLAGS_EXPR_CMD} -- "${_flags_opt_}" : '-\(.*\)'`
+          _flags_opt_=`${FLAGS_EXPR_CMD} "${_flags_opt_}" : '-\(.*\)'`
         fi
         _flags_len_=${__FLAGS_LEN_SHORT}
         if _flags_itemInList "${_flags_opt_}" ${__flags_shortNames}; then
@@ -826,12 +881,12 @@ _flags_parseGetopt()
       if [ ${FLAGS_help} -eq ${FLAGS_TRUE} ]; then
         flags_help
         flags_error='help requested'
-        flags_return=${FLAGS_TRUE}
+        flags_return=${FLAGS_FALSE}
         break
       fi
     fi
 
-    # shift the option and non-boolean arguements out.
+    # shift the option and non-boolean arguments out.
     shift
     [ ${_flags_type_} != ${__FLAGS_TYPE_BOOLEAN} ] && shift
   done
@@ -856,8 +911,7 @@ _flags_parseGetopt()
 #   integer: the result
 # Returns:
 #   bool: success of math evaluation
-_flags_math()
-{
+_flags_math() {
   if [ $# -eq 0 ]; then
     flags_return=${FLAGS_FALSE}
   elif _flags_useBuiltin; then
@@ -892,7 +946,7 @@ _flags_strlen()
   elif _flags_useBuiltin; then
     flags_output=${#_flags_str_}
   else
-    flags_output=`${FLAGS_EXPR_CMD} -- "${_flags_str_}" : '.*'`
+    flags_output=`${FLAGS_EXPR_CMD} "${_flags_str_}" : '.*'`
   fi
   flags_return=$?
 
@@ -907,18 +961,15 @@ _flags_strlen()
 #   None
 # Returns:
 #   bool: true if built-ins should be used
-_flags_useBuiltin()
-{
-  return ${__FLAGS_USE_BUILTIN}
-}
+_flags_useBuiltin() { return ${__FLAGS_USE_BUILTIN}; }
 
 #------------------------------------------------------------------------------
 # public functions
-# 
+#
 # A basic boolean flag. Boolean flags do not take any arguments, and their
 # value is either 1 (false) or 0 (true). For long flags, the false value is
 # specified on the command line by prepending the word 'no'. With short flags,
-# the presense of the flag toggles the current value between true and false.
+# the presence of the flag toggles the current value between true and false.
 # Specifying a short boolean flag twice on the command results in returning the
 # value back to the default value.
 #
@@ -1146,11 +1197,21 @@ flags_reset()
     eval ${flags_strToEval_}
   done
 
-  # reset internal variables
+  # Reset internal variables.
   __flags_boolNames=' '
   __flags_longNames=' '
   __flags_shortNames=' '
   __flags_definedNames=' '
 
+  # Reset logging level back to default.
+  flags_setLoggingLevel ${__FLAGS_LEVEL_DEFAULT}
+
   unset flags_name_ flags_type_ flags_strToEval_ flags_usName_
 }
+
+#
+# Initialization
+#
+
+# Set the default logging level.
+flags_setLoggingLevel ${__FLAGS_LEVEL_DEFAULT}
