Backported from 2.1.7pre.

diff --git a/src/shflags_test_helpers b/src/shflags_test_helpers
--- a/src/shflags_test_helpers
+++ b/src/shflags_test_helpers
@@ -1,68 +1,77 @@
 # vim:et:ft=sh:sts=2:sw=2
 #
-# Copyright 2008 Kate Ward. All Rights Reserved.
-# Released under the LGPL (GNU Lesser General Public License)
+# shFlags unit test common functions
+#
+# Copyright 2008-2017 Kate Ward. All Rights Reserved.
+# Released under the Apache 2.0 license.
 #
 # Author: kate.ward@forestent.com (Kate Ward)
+# https://github.com/kward/shflags
 #
-# shFlags unit test common functions
+### ShellCheck (http://www.shellcheck.net/)
+# Disable source following.
+#   shellcheck disable=SC1090,SC1091
+# $() are not fully portable (POSIX != portable).
+#   shellcheck disable=SC2006
+# Disagree with [ p ] && [ q ] vs [ p -a -q ] recommendation.
+#   shellcheck disable=SC2166
 
-__th_skipping=0
-
-# treat unset variables as an error
+# Treat unset variables as an error.
 set -u
 
-# set shwordsplit for zsh
+# Set shwordsplit for zsh.
 [ -n "${ZSH_VERSION:-}" ] && setopt shwordsplit
 
-# my name
-TH_MY_NAME=`basename "$0"`
+# Message functions.
+th_trace() { echo "test:TRACE $*" >&2; }
+th_debug() { echo "test:DEBUG $*" >&2; }
+th_info() { echo "test:INFO $*" >&2; }
+th_warn() { echo "test:WARN $*" >&2; }
+th_error() { echo "test:ERROR $*" >&2; }
+th_fatal() { echo "test:FATAL $*" >&2; exit 1; }
 
-# path to shFlags library. can be overridden by setting SHFLAGS_INC
-TH_SHFLAGS=${SHFLAGS_INC:-./shflags}
+# My name.
+TH_MY_NAME=`basename "$0"` || th_fatal 'Error executing basename.'
+export TH_MY_NAME
 
-# path to shUnit2 library. can be overridden by setting SHUNIT_INC
-TH_SHUNIT=${SHUNIT_INC:-../lib/shunit2}
+# Path to shFlags library. Can be overridden by setting SHFLAGS_INC.
+export TH_SHFLAGS=${SHFLAGS_INC:-./shflags}
 
-TH_BOOL_VALID='true t 0 false f 1'
-TH_BOOL_INVALID='123 123.0 blah'
-TH_FLOAT_VALID='-1234.0 -1234 -1.0 -1 0.0 0 1.0 1 1234.0 1234'
-TH_FLOAT_INVALID='true false invalid 1.2.3 -1.2.3 0. -.5'
-TH_INT_VALID='-1234 -1 0 1 1234'
-TH_INT_INVALID='-1.0 0.0 1.0 invalid'
+# Path to shUnit2 library. Can be overridden by setting SHUNIT_INC.
+export TH_SHUNIT=${SHUNIT_INC:-../lib/shunit2}
+
+export TH_BOOL_VALID='true t 0 false f 1'
+export TH_BOOL_INVALID='123 123.0 invalid'
+export TH_FLOAT_VALID='-1234.0 -1.0 -.123 0.0 0. .123 1.0 1234.0'
+export TH_FLOAT_INVALID='true false 1.2.3 -1.2.3 ""'
+export TH_INT_VALID='-1234 -1 0 1 1234'
+export TH_INT_INVALID='true false -1.0 -.123 0.0 .123 1.0 ""'
 
 #
-# test helper functions
+# Test helper functions.
 #
 
-# message functions
-th_trace() { echo "test:TRACE $@" >&2; }
-th_debug() { echo "test:DEBUG $@" >&2; }
-th_info() { echo "test:INFO $@" >&2; }
-th_warn() { echo "test:WARN $@" >&2; }
-th_error() { echo "test:ERROR $@" >&2; }
-th_fatal() { echo "test:FATAL $@" >&2; }
-
-th_oneTimeSetUp()
-{
+th_oneTimeSetUp() {
   # Load shFlags.
+  # shellcheck disable=SC2034
   [ -n "${ZSH_VERSION:-}" ] && FLAGS_PARENT=$0
-  . ${TH_SHFLAGS}
+  . "${TH_SHFLAGS}"
 
   # These files will be cleaned up automatically by shUnit2.
-  stdoutF="${SHUNIT_TMPDIR}/stdout"
-  stderrF="${SHUNIT_TMPDIR}/stderr"
-  expectedF="${SHUNIT_TMPDIR}/expected"
+  export tmpDir=${SHUNIT_TMPDIR}
+  stdoutF="${tmpDir}/stdout" && touch "${stdoutF}"
+  stderrF="${tmpDir}/stderr" && touch "${stderrF}"
+  returnF="${tmpDir}/return" && touch "${returnF}"
+  expectedF="${tmpDir}/expected" && touch "${expectedF}"
 }
 
-th_showOutput()
-{
+th_showOutput() {
   _th_rtrn=$1
   _th_stdout=$2
   _th_stderr=$3
 
   isSkipping
-  if [ $? -eq ${SHUNIT_FALSE} -a ${_th_rtrn} != ${FLAGS_TRUE} ]; then
+  if [ $? -eq "${SHUNIT_FALSE}" -a "${_th_rtrn}" != "${FLAGS_TRUE}" ]; then
     if [ -n "${_th_stdout}" -a -s "${_th_stdout}" ]; then
       echo '>>> STDOUT' >&2
       cat "${_th_stdout}" >&2
@@ -72,15 +81,27 @@ th_showOutput()
       cat "${_th_stderr}" >&2
     fi
     if [ -n "${_th_stdout}" -o -n "${_th_stderr}" ]; then
-      echo '>>> end output' >&2
+      echo '<<< end output' >&2
     fi
   fi
 
   unset _th_rtrn _th_stdout _th_stderr
 }
 
-_th_assertMsg()
-{
+# Some shells, zsh on Solaris in particular, return immediately from a sub-shell
+# when a non-zero return value is encountered. To properly catch these values,
+# they are either written to disk, or recognized as an error the file is empty.
+th_clearReturn() { cp /dev/null "${returnF}"; }
+th_queryReturn() {
+  if [ -s "${returnF}" ]; then
+    cat "${returnF}"
+    return $?
+  fi
+  echo "${SHUNIT_ERROR}"
+  return "${SHUNIT_ERROR}"
+}
+
+_th_assertMsg() {
   _th_alert_type_=$1
   _th_alert_msg_=$2
   _th_msg_=$3
