Fixed issue #43. Added support for BusyBox ash shell.

diff --git a/src/shflags b/src/shflags
--- a/src/shflags
+++ b/src/shflags
@@ -82,11 +82,11 @@
 # Notes:
 # - lists of strings are space separated, and a null value is the '~' char.
 
-# return if FLAGS already loaded
+# Return if FLAGS already loaded.
 [ -n "${FLAGS_VERSION:-}" ] && return 0
-FLAGS_VERSION='1.2.0'
+FLAGS_VERSION='1.2.1'
 
-# return values that scripts can use
+# Return values that scripts can use.
 FLAGS_TRUE=0
 FLAGS_FALSE=1
 FLAGS_ERROR=2
@@ -100,17 +100,24 @@ FLAGS_LEVEL_FATAL=4
 __FLAGS_LEVEL_DEFAULT=${FLAGS_LEVEL_WARN}
 
 # Determine some reasonable command defaults.
+__FLAGS_EXPR_CMD='expr --'
 __FLAGS_UNAME_S=`uname -s`
-case "${__FLAGS_UNAME_S}" in
-  BSD) __FLAGS_EXPR_CMD='gexpr' ;;
-  *) __FLAGS_EXPR_CMD='expr' ;;
-esac
+if [ "${__FLAGS_UNAME_S}" = 'BSD' ]; then
+  __FLAGS_EXPR_CMD='gexpr --'
+else
+  _flags_output_=`${__FLAGS_EXPR_CMD} 2>&1`
+  if [ $? -eq ${FLAGS_TRUE} -a "${_flags_output_}" = '--' ]; then
+    # We are likely running inside BusyBox.
+    __FLAGS_EXPR_CMD='expr'
+  fi
+  unset _flags_output_
+fi
 
-# commands a user can override if needed
+# Commands a user can override if needed.
 FLAGS_EXPR_CMD=${FLAGS_EXPR_CMD:-${__FLAGS_EXPR_CMD}}
 FLAGS_GETOPT_CMD=${FLAGS_GETOPT_CMD:-getopt}
 
-# specific shell checks
+# Specific shell checks.
 if [ -n "${ZSH_VERSION:-}" ]; then
   setopt |grep "^shwordsplit$" >/dev/null
   if [ $? -ne ${FLAGS_TRUE} ]; then
@@ -122,7 +129,7 @@ if [ -n "${ZSH_VERSION:-}" ]; then
   fi
 fi
 
-# can we use built-ins?
+# Can we use built-ins?
 ( echo "${FLAGS_TRUE#0}"; ) >/dev/null 2>&1
 if [ $? -eq ${FLAGS_TRUE} ]; then
   __FLAGS_USE_BUILTIN=${FLAGS_TRUE}
@@ -132,14 +139,14 @@ fi
 
 
 #
-# constants
+# Constants.
 #
 
-# reserved flag names
+# Reserved flag names.
 __FLAGS_RESERVED_LIST=' ARGC ARGV ERROR FALSE GETOPT_CMD HELP PARENT TRUE '
 __FLAGS_RESERVED_LIST="${__FLAGS_RESERVED_LIST} VERSION "
 
-# getopt version
+# getopt version.
 __FLAGS_GETOPT_VERS_STD=0
 __FLAGS_GETOPT_VERS_ENH=1
 __FLAGS_GETOPT_VERS_BSD=2
@@ -147,6 +154,7 @@ __FLAGS_GETOPT_VERS_BSD=2
 ${FLAGS_GETOPT_CMD} >/dev/null 2>&1
 case $? in
   0) __FLAGS_GETOPT_VERS=${__FLAGS_GETOPT_VERS_STD} ;;  # bsd getopt
+  1) __FLAGS_GETOPT_VERS=${__FLAGS_GETOPT_VERS_ENH} ;;  # BusyBox getopt.
   2)
     # TODO(kward): look into '-T' option to test the internal getopt() version
     if [ "`${FLAGS_GETOPT_CMD} --version`" = '-- ' ]; then
@@ -164,40 +172,40 @@ __FLAGS_OPTSTR_LONG=1
 
 __FLAGS_NULL='~'
 
-# flag info strings
+# Flag info strings.
 __FLAGS_INFO_DEFAULT='default'
 __FLAGS_INFO_HELP='help'
 __FLAGS_INFO_SHORT='short'
 __FLAGS_INFO_TYPE='type'
 
-# flag lengths
+# Flag lengths.
 __FLAGS_LEN_SHORT=0
 __FLAGS_LEN_LONG=1
 
-# flag types
+# Flag types.
 __FLAGS_TYPE_NONE=0
 __FLAGS_TYPE_BOOLEAN=1
 __FLAGS_TYPE_FLOAT=2
 __FLAGS_TYPE_INTEGER=3
 __FLAGS_TYPE_STRING=4
 
-# set the constants readonly
+# Set the constants readonly.
 __flags_constants=`set |awk -F= '/^FLAGS_/ || /^__FLAGS_/ {print $1}'`
 for __flags_const in ${__flags_constants}; do
-  # skip certain flags
+  # Skip certain flags.
   case ${__flags_const} in
     FLAGS_HELP) continue ;;
     FLAGS_PARENT) continue ;;
   esac
-  # set flag readonly
+  # Set flag readonly.
   if [ -z "${ZSH_VERSION:-}" ]; then
     readonly ${__flags_const}
-  else  # handle zsh
-    case ${ZSH_VERSION} in
-      [123].*) readonly ${__flags_const} ;;
-      *) readonly -g ${__flags_const} ;;  # declare readonly constants globally
-    esac
+    continue
   fi
+  case ${ZSH_VERSION} in
+    [123].*) readonly ${__flags_const} ;;
+    *) readonly -g ${__flags_const} ;;  # Declare readonly constants globally.
+  esac
 done
 unset __flags_const __flags_constants
 
@@ -588,8 +596,7 @@ _flags_validBool()
 #   _flags_float_: float: value to validate
 # Returns:
 #   bool: true if the value is a valid integer
-_flags_validFloat()
-{
+_flags_validFloat() {
   flags_return=${FLAGS_FALSE}
   [ -n "$1" ] || return ${flags_return}
   _flags_float_=$1
@@ -608,11 +615,11 @@ _flags_validFloat()
     flags_return=${FLAGS_TRUE}
     case ${_flags_float_} in
       -*)  # negative floats
-        _flags_test_=`${FLAGS_EXPR_CMD} -- "${_flags_float_}" :\
+        _flags_test_=`${FLAGS_EXPR_CMD} "${_flags_float_}" :\
             '\(-[0-9]*\.[0-9]*\)'`
         ;;
       *)  # positive floats
-        _flags_test_=`${FLAGS_EXPR_CMD} -- "${_flags_float_}" :\
+        _flags_test_=`${FLAGS_EXPR_CMD} "${_flags_float_}" :\
             '\([0-9]*\.[0-9]*\)'`
         ;;
     esac
@@ -642,7 +649,7 @@ _flags_validInt()
       if _flags_useBuiltin; then
         _flags_int_=${_flags_int_#-}
       else
-        _flags_int_=`${FLAGS_EXPR_CMD} -- "${_flags_int_}" : '-\([0-9][0-9]*\)'`
+        _flags_int_=`${FLAGS_EXPR_CMD} "${_flags_int_}" : '-\([0-9][0-9]*\)'`
       fi
       ;;
   esac
@@ -774,7 +781,7 @@ _flags_parseGetopt()
         if _flags_useBuiltin; then
           _flags_opt_=${_flags_opt_#*--}
         else
-          _flags_opt_=`${FLAGS_EXPR_CMD} -- "${_flags_opt_}" : '--\(.*\)'`
+          _flags_opt_=`${FLAGS_EXPR_CMD} "${_flags_opt_}" : '--\(.*\)'`
         fi
         _flags_len_=${__FLAGS_LEN_LONG}
         if _flags_itemInList "${_flags_opt_}" ${__flags_longNames}; then
@@ -785,7 +792,7 @@ _flags_parseGetopt()
             if _flags_useBuiltin; then
               _flags_name_=${_flags_opt_#*no}
             else
-              _flags_name_=`${FLAGS_EXPR_CMD} -- "${_flags_opt_}" : 'no\(.*\)'`
+              _flags_name_=`${FLAGS_EXPR_CMD} "${_flags_opt_}" : 'no\(.*\)'`
             fi
             _flags_type_=${__FLAGS_TYPE_BOOLEAN}
             _flags_arg_=${__FLAGS_NULL}
@@ -797,7 +804,7 @@ _flags_parseGetopt()
         if _flags_useBuiltin; then
           _flags_opt_=${_flags_opt_#*-}
         else
-          _flags_opt_=`${FLAGS_EXPR_CMD} -- "${_flags_opt_}" : '-\(.*\)'`
+          _flags_opt_=`${FLAGS_EXPR_CMD} "${_flags_opt_}" : '-\(.*\)'`
         fi
         _flags_len_=${__FLAGS_LEN_SHORT}
         if _flags_itemInList "${_flags_opt_}" ${__flags_shortNames}; then
@@ -904,8 +911,7 @@ _flags_parseGetopt()
 #   integer: the result
 # Returns:
 #   bool: success of math evaluation
-_flags_math()
-{
+_flags_math() {
   if [ $# -eq 0 ]; then
     flags_return=${FLAGS_FALSE}
   elif _flags_useBuiltin; then
@@ -940,7 +946,7 @@ _flags_strlen()
   elif _flags_useBuiltin; then
     flags_output=${#_flags_str_}
   else
-    flags_output=`${FLAGS_EXPR_CMD} -- "${_flags_str_}" : '.*'`
+    flags_output=`${FLAGS_EXPR_CMD} "${_flags_str_}" : '.*'`
   fi
   flags_return=$?
 
